// The card is drawn in a worker, where there are no fonts, .ttf cannot be
// imported as bytes and a fetch would depend on which host the worker thinks
// it is answering for. So the face is carried in the bundle.
// Regenerate with: bun run scripts/build-card-font.ts
import { readFile, writeFile } from 'node:fs/promises';

const SOURCE = 'public/fonts/card.ttf';
const OUT = 'src/lib/og/card-font-data.ts';

const bytes = await readFile(SOURCE);
await writeFile(
  OUT,
  `/** Rubik Medium, for the link-preview card. Generated by\n *  scripts/build-card-font.ts — do not edit by hand. */\nexport const CARD_FONT_BASE64 =\n  '${bytes.toString('base64')}';\n`,
);
console.log(`${SOURCE} → ${OUT} (${Math.round(bytes.byteLength / 1024)} KB)`);
