// The card is drawn in a worker, where there are no fonts, .ttf cannot be
// imported as bytes and a fetch would depend on which host the worker thinks
// it is answering for. So the faces are carried in the bundle.
//
// Both are static instances pulled from Google Fonts as TrueType — the woff2
// the modern API serves is not something the renderer can open:
//   Fraunces: css2?family=Fraunces:opsz,wght@72,700  (legacy user agent)
//   Rubik:    css?family=Rubik:500                   (legacy user agent)
// Regenerate with: bun run scripts/build-card-font.ts
import { readFile, writeFile } from 'node:fs/promises';

const FACES = [
  { source: 'public/fonts/card-title.ttf', out: 'card-title-font-data', name: 'CARD_TITLE_FONT_BASE64', what: 'Fraunces 72pt Bold, for the title' },
  { source: 'public/fonts/card.ttf', out: 'card-text-font-data', name: 'CARD_TEXT_FONT_BASE64', what: 'Rubik Medium, for everything else — and the only Cyrillic here' },
] as const;

const build = async (face: (typeof FACES)[number]): Promise<string> => {
  const bytes = await readFile(face.source);
  await writeFile(
    `src/lib/og/${face.out}.ts`,
    `/** ${face.what}. Generated by\n *  scripts/build-card-font.ts — do not edit by hand. */\nexport const ${face.name} =\n  '${bytes.toString('base64')}';\n`,
  );
  return `${face.source} → src/lib/og/${face.out}.ts (${Math.round(bytes.byteLength / 1024)} KB)`;
};

const built = await Promise.all(FACES.map(build));
built.forEach((line) => console.log(line));
